//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem4.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int idPersona { get; set; }
        public string Identificación { get; set; }
        public string nomPersona { get; set; }
        public string Ape1Persona { get; set; }
        public string Ape2Persona { get; set; }
    }
}
